name: ideabench_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.7.0
  - anyio=4.4.0
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cachetools=5.4.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.2
  - cryptography=42.0.8
  - dataclasses-json=0.5.7
  - debugpy=1.8.2
  - decorator=5.1.1
  - distro=1.9.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - frozenlist=1.4.1
  - google-api-core=2.19.1
  - google-auth=2.32.0
  - googleapis-common-protos=1.63.2
  - greenlet=3.0.3
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keyutils=1.6.1
  - krb5=1.21.3
  - langchain=0.2.10
  - langchain-openai=0.1.17
  - langchain-text-splitters=0.2.2
  - langsmith=0.1.93
  - ld_impl_linux-64=2.40
  - libabseil=20240116.2
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - marshmallow=3.21.3
  - marshmallow-enum=1.5.1
  - matplotlib-inline=0.1.7
  - multidict=6.0.5
  - mypy_extensions=1.0.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=1.37.0
  - openapi-schema-pydantic=1.2.4
  - openssl=3.3.1
  - orjson=3.10.6
  - packaging=23.2
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - proto-plus=1.23.0
  - protobuf=4.25.3
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.0
  - pyasn1-modules=0.4.0
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyopenssl=24.2.1
  - pysocks=1.7.1
  - python=3.12.4
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - readline=8.2
  - regex=2024.5.15
  - requests=2.32.3
  - rsa=4.9
  - setuptools=71.0.4
  - six=1.16.0
  - sniffio=1.3.1
  - sqlalchemy=2.0.31
  - stack_data=0.6.2
  - stringcase=1.2.0
  - tenacity=8.5.0
  - tiktoken=0.7.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_inspect=0.9.0
  - tzdata=2024a
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zeromq=4.3.5
  - zipp=3.19.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==0.33.0
      - bert-score==0.3.13
      - click==8.1.7
      - contourpy==1.2.1
      - cycler==0.12.1
      - datasets==2.20.0
      - dill==0.3.8
      - evaluate==0.4.2
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.5.0
      - google-ai-generativelanguage==0.6.6
      - google-api-python-client==2.139.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.7.2
      - groq==0.9.0
      - grpcio==1.65.1
      - grpcio-status==1.62.2
      - httplib2==0.22.0
      - huggingface-hub==0.24.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - langchain-community==0.2.10
      - langchain-core==0.2.26
      - langchain-experimental==0.0.63
      - langchain-google-genai==1.0.8
      - langchain-groq==0.1.9
      - langchain-huggingface==0.0.3
      - llamaapi==0.1.36
      - markupsafe==2.1.5
      - matplotlib==3.9.1
      - mpmath==1.3.0
      - multiprocess==0.70.16
      - networkx==3.3
      - nltk==3.8.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.82
      - nvidia-nvtx-cu12==12.1.105
      - patsy==0.5.6
      - pillow==10.4.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pyparsing==3.1.2
      - rouge-score==0.1.2
      - safetensors==0.4.3
      - scikit-learn==1.5.1
      - scipy==1.14.0
      - seaborn==0.13.2
      - sentence-transformers==3.0.1
      - statsmodels==0.14.2
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - torch==2.3.1
      - transformers==4.43.1
      - uritemplate==4.1.1
      - xxhash==3.4.1
